name: Main workflow

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gconf2
          version: 1.0
        if: matrix.os == 'ubuntu-latest'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: bats -r test/*.bats
